// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteRedisKey(arg1:string):Promise<void>;

export function GetConfig():Promise<models.Config>;

export function GetRedisKeys(arg1:string):Promise<Array<models.RedisKey>>;

export function GetUsers():Promise<Array<models.User>>;

export function SimulateRating(arg1:models.RatingSimInput):Promise<models.RatingSimResult>;

export function UpdateUserRankScore(arg1:number,arg2:number):Promise<void>;
