// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRedisKey(arg1) {
  return window['go']['main']['App']['DeleteRedisKey'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigHistory() {
  return window['go']['main']['App']['GetConfigHistory']();
}

export function GetRedisKeys(arg1) {
  return window['go']['main']['App']['GetRedisKeys'](arg1);
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function RestoreConfig(arg1) {
  return window['go']['main']['App']['RestoreConfig'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SimulateRating(arg1) {
  return window['go']['main']['App']['SimulateRating'](arg1);
}

export function UpdateUserRankScore(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserRankScore'](arg1, arg2);
}

export function UploadMatchResult(arg1) {
  return window['go']['main']['App']['UploadMatchResult'](arg1);
}
